language: php
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit
warnings_are_errors: true
services:
  - mysql
php:
  - 7.4

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini

install:
  - composer install --prefer-dist --no-interaction --dev
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpdbg -qrr -d memory_limit=-1 ./vendor/bin/simple-phpunit  --colors --coverage-clover ./coverage.xml
  - ./vendor/bin/grumphp run

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL